// components/Sponsor.tsx
import React, {ReactElement} from "react";
import NavLink from './NavLink';

export interface SponsorProps {

    name: string;
    logo: string;
    link: string;
    description: string;
}

export default function Sponsor({name, logo, link, description} : SponsorProps): ReactElement {

    return (
        <div className="text-center text-white m-2 p-2 md:mb-5 md:p-5 border border-white rounded-lg bg-blue-500 bg-opacity-20 shadow-lg">

            <img src={logo} className="w-48 h-48 m-auto glowyimg" width="192px" height="192px" alt={name}/>

            <div className="text-center">
                <h3><NavLink title={name} location={link} inline={true}/></h3>
                <p>{description}</p>
            </div>
        </div>
    );
}

// src/components/Sponsor.svelte
<script lang="ts">
	import classNames from 'classnames';

	export let name: string;
	export let logo: string | undefined = undefined;
	export let href: string | undefined = undefined;
	export let target: string | undefined = '_blank';
	export let rel: string | undefined = 'noopener noreferrer';
	export let reverse: boolean = true;
</script>

<a
	{href}
	{target}
	{rel}
	title={name}
	class={classNames(
		'bg-white dark:bg-gray-800 text-gray-500 dark:text-gray-400 bg-opacity-30 border border-gray-200 dark:border-gray-700 divide-gray-200 dark:divide-gray-700 shadow-md flex max-w-sm md:max-w-xl hover:bg-gray-100 dark:hover:bg-gray-700 mb-4 flex-col p-6 items-center gap-2',
		reverse ? 'md:flex-row-reverse' : 'md:flex-row'
	)}
>
	<enhanced:img
		src={logo}
		alt={name}
		class="p-1 ring-2 ring-gray-300 dark:ring-gray-500 w-32 h-32 bg-gray-100 dark:bg-gray-600 text-gray-600 dark:text-gray-300 rounded-full m-auto"
		loading="lazy"
	/>
	<div class="max-w-sm flex items-center flex-col leading-tight">
		<h2 class="tracking-wide">{name}</h2>
		<span class="inline-block text-center tracking-tight">
			<slot />
		</span>
	</div>
</a>
