// src/routes/faq/+page.svelte
<script>
	import ExternalLink from '$components/ExternalLink.svelte';
	import Meta from '$components/Meta.svelte';
</script>

<Meta title="FAQ" />
<h1>WinterJam 2023 FAQ</h1>

<ol
	class="text-justify md:child:text-xl child:text-lg child:rounded-lg child:bg-slate-950 child:bg-opacity-30 child:p-4"
>
	<li>
		<h4>Can I submit multiple mods to this event?</h4>
		<span>
			Yes, you may create and submit multiple submissions to this event.<br />
			If you plan on doing so, please take care of yourself and take steps to avoid stress and burnout.
		</span>
	</li>
	<li>
		<h4>Can I team up with a friend?</h4>
		<span>
			Teams are allowed! There are no hard limits to the size of a team, however we suggest maximum
			teams of roughly 4 or 5.
		</span>
	</li>
	<li>
		<h4>Can I join multiple teams?</h4>
		<span>
			Yes, you may join and contribute to multiple teams. If want to do this, you should be
			transparent with everyone in your team about other teams you are contributing to.
		</span>
	</li>
	<li>
		<h4>Can I submit the same mod on multiple modloaders?</h4>
		<span>
			While Forge is the primary modloader for this event, others are allowed. However, only mods
			compatible with Forge or <ExternalLink
				href="https://www.curseforge.com/minecraft/mc-mods/sinytra-connector"
				class="underline">Sinytra Connector</ExternalLink
			> will be added to the pack.<br />
			Be advised that supporting multiple loaders is completely optional. Doing so will require additional
			effort and may be stressful.<br />
			If you're still interested in doing so, you can use <ExternalLink
				href="https://github.com/architectury/architectury-templates"
				class="underline">Architectury</ExternalLink
			> or <ExternalLink href="https://github.com/jaredlll08/MultiLoader-Template" class="underline"
				>Jared's MultiLoader Template</ExternalLink
			> to help with this.
		</span>
	</li>
	<li>
		<h4>I am not a mod author, how can I participate?</h4>
		<span>
			Everyone is welcome to participate even if you're not a mod author!<br />
			One of the easiest ways to join in is by giving participants feedback and encouragement or play
			with the mods on the public Minecraft server.<br />
			If you're looking to get more involved you may be able to help with translating submissions, helping
			with textures/models, or contributing in other ways.<br />
			You can also use this opportunity to learn more about mod development and try to make your own
			mods in the future!
		</span>
	</li>
	<li>
		<h4>Can I submit a mod from previous WinterJam events?</h4>
		<span>
			Yes, previous year entries that have been updated can be resubmitted.<br />
			These entries will not receive the same level of promotion that new submissions receive, however
			they may be included on our modpack and server.
		</span>
	</li>
	<li>
		<h4>Do Pull Requests count as being a team member?</h4>
		<span>
			Creating a Pull Request does not inherently make you a member of that team.<br />
			The team list is ultimately up to that team as a whole.
		</span>
	</li>
	<li>
		<h4>Can I submit a mod that I did not create?</h4>
		<span>
			No. Only the authors of a project may submit it to WinterJam, however you can request that the
			events team add a previous entry if it is up to date and supported by the pack and server.
		</span>
	</li>
	<li>
		<h4>Do I need to submit my project?</h4>
		<span>
			Yes you must submit your project before the event deadline via the submissions form.<br />
			(Your submission will only be counted if you are a member of the <ExternalLink
				href="/discord"
				class="underline">Minecraft Mod Development discord server</ExternalLink
			> where the event is hosted)<br />
			<a class="font-bold underline hover:text-important focus:text-important" href="/jams/2023/submit">Click here to submit your project!</a>
		</span>
	</li>
	<li>
		<h4>How should teams submit their project?</h4>
		<span>
			Teams should select one team member to submit their project.<br />
			Submitting the same project multiple times is not required for updates.
		</span>
	</li>
	<li>
		<h4>Can I ask for an unrelated mod be added to the pack such as HWYLA?</h4>
		<span>
			You can request the events team add other mods to the pack during or after creation, though
			they have the final say if it fits and doesn't overshadow/distract from the creations
			submitted for this jam.
		</span>
	</li>
</ol>

// pages/faq.tsx
import type { NextPage } from "next";
import { Layout } from "../components/";
import NavLink from "../components/NavLink";

const FaqPage: NextPage = () => {
    return (
        <Layout title="FAQ" url="/faq">
            <div className="lg:w-3/4 md:w-5/6 mx-auto text-primary text-xl text-center list-inside">
                <h2>Frequently Asked Questions</h2>
                <h3>Can I submit multiple mods to this event?</h3>
                <p className="mb-10">
                    Yes, you may create and submit multiple submissions to this event.
                    If you plan on doing so, please take care of yourself and take steps to avoid stress and burnout.
                </p>

                <h3>Can I join multiple teams?</h3>
                <p className="mb-10">
                    Yes, you may join and contribute to multiple teams. If want to do this,
                    we recommend being transparent with all of your team mates about other teams you are contributing to.
                </p>
                <h3>Can I submit the same mod on multiple modloaders?</h3>
                <p className="mb-10">
                    Yes, you may support both Forge and Quilt with your submission. Please be
                    advised that supporting both loaders is completely optional. Doing so
                    will require additional effort and may be stressful. If you&apos;re
                    still interested in doing so, we recommend checking
                    out <NavLink title='MultiLoader-Template' location='https://github.com/jaredlll08/MultiLoader-Template' inline />.
                </p>

                <h3>I am not a mod author, how can I participate?</h3>
                <p className="mb-10">
                    Everyone is welcome to participate in WinterJam. One of the easiest
                    ways to join in is by giving participants feedback and encouragement
                    or play with the mods on the public Minecraft servers. If
                    you&apos;re looking to get more involved with the event you may be
                    able to help with translating submissions, helping with textures, or
                    contributing in other ways. WinterJam is also a great opportunity to
                    learn more about mod development and try to make your own mods.
                </p>

                <h3>Can I submit a mod from previous WinterJam events?</h3>
                <p className="mb-10">
                    Yes, previous year entries that have been updated can be resubmitted.
                    These entries will not receive the same level of promotion that new
                    submissions receive, however they may be included on our modpacks and servers.
                </p>

                <h3>Do Pull Requests count as being a team member?</h3>
                <p className="mb-10">
                    Creating a Pull Request does not inherently make you a member of that
                    team. The team list is ultimately up to that team and the member who
                    is submitting their submission. The event organizers will
                    step in is when the Pull Request System is being abused to bypass
                    event rules.
                </p>

                <h3>
                    Would accepting a Pull Request from an ineligible person make my
                    project ineligible for prizes?
                </h3>
                <p className="mb-10">
                    Accepting minor Pull Requests from an ineligible person is fine. A
                    minor Pull Request in this context would be along the lines of fixing
                    a typo or bug, resource optimization, or localizing the mod to another
                    language.
                </p>

                <h3>Does the mod need to be published on CurseForge?</h3>
                <p className="mb-10">
                    We are only accepting mods that have been published to CurseForge.
                    Having this requirement allows us to streamline the process of
                    publishing the modpack and having players connect to our servers.
                </p>

                <h3>Can I submit a mod that I did not create?</h3>
                <p className="mb-10">
                    No. Only the authors of a project may submit it to WinterJam.
                    </p>

                <h3>How should teams submit their project?</h3>
                <p className="mb-10">
                    Teams should select one team member to submit their project.
                    Submitting the same project multiple times is not needed.
                </p>

                <h3>Do I need to submit my project?</h3>
                <p className="mb-10">
                    Yes you must submit your project before the event deadline via the submissions form
                    on the top of this page. (Your submission will only be counted if you are a member
                    of MMD&apos;s Discord server)
                </p>
            </div>
        </Layout>
    );
};

export default FaqPage;
